pollProject/pollApp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('home/', views.home, name='home'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pollProject/pollProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from pollApp import views
from voteStatistics import views as vote_stats_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include('accounts.urls', namespace="accounts")),
    path('', include('landingPage.urls')),
    path('polls/', include('pollApp.urls')),
    path('statistics/', include('voteStatistics.urls', namespace='voteStatistics')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pollProject/voteStatistics/urls.py
from django.urls import path
from . import views

app_name = 'voteStatistics'

urlpatterns = [
    path('', views.vote_statistics, name='vote_statistics'),
    path('category_statistics/', views.category_statistics, name='category_statistics'),  # Add a named pattern for your view
]

pollProject/voteStatistics/models.py
from django.db import models

# Create your models here.

pollProject/voteStatistics/views.py
from django.shortcuts import render
from django.db.models import Sum, F
from accounts.models import CustomUser
from pollApp.models import Vote, Question, Season, Category
import json
from django.contrib.auth.decorators import login_required, user_passes_test
from pollApp.models import Choice

def is_admin(user):
    return user.is_superuser

@login_required
@user_passes_test(is_admin)
def vote_statistics(request):
    selected_year = request.GET.get('year')
    selected_season_id = request.GET.get('season')
    selected_question_id = request.GET.get('question')

    years = Season.objects.values_list('year', flat=True).distinct()
    seasons = Season.objects.all()
    all_questions = Question.objects.all().distinct()
    age_ranges = [(0, 12), (13, 17), (18, 25), (26, 35), (36, 45), (46, 55), (56, 65), (66, 100)]
    if selected_year:
        seasons = seasons.filter(year=selected_year)
        all_questions = all_questions.filter(vote__year=selected_year)

    if selected_season_id:
        all_questions = all_questions.filter(vote__season__id=selected_season_id)

    questions = all_questions

    if selected_question_id:
        questions = questions.filter(id=selected_question_id)

    question_votes = []

    for question in questions:
        top_votes_qs = Vote.objects.filter(question=question)

        if selected_year:
            top_votes_qs = top_votes_qs.filter(year=selected_year)

        if selected_season_id:
            top_votes_qs = top_votes_qs.filter(season__id=selected_season_id)

        top_votes_qs = top_votes_qs.values('choice__choice_text').annotate(total_votes=Sum('votes')).order_by('-total_votes')[:10]

        for vote in top_votes_qs:
            voters = CustomUser.objects.filter(vote__choice__choice_text=vote['choice__choice_text'])
            vote['voters'] = list(voters.values('username', 'region', 'gender', 'age'))

            total_voters = voters.count()
            vote['gender_percentage'] = {gender[1]: voters.filter(gender=gender[0]).count() / total_voters * 100 for gender in CustomUser.GENDERS if gender[0]}
            vote['region_percentage'] = {region[1]: voters.filter(region=region[0]).count() / total_voters * 100 for region in CustomUser.REGIONS if region[0]}
            vote['age_percentage'] = {f'{age_range[0]}-{age_range[1]}': voters.filter(age__range=age_range).count() / total_voters * 100 for age_range in age_ranges}

        question_votes.append({'question': question.to_dict(), 'top_votes': list(top_votes_qs)})

    question_votes_json = json.dumps(question_votes)

    context = {
        'question_votes_json': question_votes_json,
        'question_votes': question_votes,
        'years': years,
        'seasons': seasons,
        'all_questions': all_questions,
        'selected_year': selected_year,
        'selected_season': int(selected_season_id) if selected_season_id else None,
        'selected_question': int(selected_question_id) if selected_question_id else None,
    }

    return render(request, 'voteStatistics/vote_statistics.html', context)

@login_required
@user_passes_test(is_admin)
def category_statistics(request):
    all_categories = Category.objects.all()
    selected_category_name = request.GET.get('category')

    questions = Question.objects.all()
    if selected_category_name:
        questions = questions.filter(category__name=selected_category_name)

    categories = {}
    season_votes = {}

    # Count the number of votes for each season within the selected category
    for question in questions:
        for season in question.seasons.all():
            if season not in season_votes:
                season_votes[season] = 0
            season_votes[season] += Vote.objects.filter(question=question, season=season).count()

    total_votes = sum(season_votes.values())

    for question in questions:
        if question.category not in categories:
            categories[question.category] = {}

        for season in question.seasons.all():
            if season not in categories[question.category]:
                categories[question.category][season] = {
                    'questions': []
                }

            choice_votes = Vote.objects.filter(question=question, season=season).values('choice__choice_text').annotate(total_votes=Sum('votes'))
            total_question_votes = sum(vote['total_votes'] for vote in choice_votes)

            question_data = {
                'question': question,
                'choice_votes': choice_votes,
                'total_votes': total_question_votes,
                'weighted_scores': {}  # Placeholder for weighted scores
            }
            categories[question.category][season]['questions'].append(question_data)

    # Calculate weights and weighted scores
    for category, seasons in categories.items():
        for season, data in seasons.items():
            # Calculate the weight for the current season
            weight = season_votes[season] / total_votes
            for question_data in data['questions']:
                total_question_votes = question_data['total_votes']
                for vote in question_data['choice_votes']:
                    # Calculate the percentage of votes for the current choice
                    percentage = vote['total_votes'] / total_question_votes
                    # Calculate the weighted score for the current choice
                    weighted_score = percentage * weight
                    # Store the weight and weighted score in the vote dictionary
                    vote['season_weight'] = weight
                    vote['weighted_score'] = weighted_score
    
    top_shows_by_category = {}
    for category, seasons in categories.items():
        top_shows = []
        for season, data in seasons.items():
            for question_data in data['questions']:
                for vote in question_data['choice_votes']:
                    # Assuming 'choice' is the foreign key to the Choice model
                    choices = Choice.objects.filter(choice_text=vote['choice__choice_text'])

                    if choices.exists():
                        # Use the first choice or handle the situation as needed
                        choice = choices.first()
                        image_path = choice.image.url  # Adjust the field name accordingly
                    else:
                        # Handle the case where no choices are found
                        image_path = "path/to/default/image.jpg"  # Adjust with the default image path

                    top_shows.append({
                        'show': vote['choice__choice_text'],
                        'weighted_score': vote['weighted_score'],
                        'choice_image': image_path,  # Include the image path
                    })
        # Sort the shows by weighted score in descending order and select the top 5
        top_shows.sort(key=lambda x: x['weighted_score'], reverse=True)
        top_shows_by_category[category] = top_shows[:5]

    return render(request, 'voteStatistics/category_statistics.html', {
        'categories': categories,
        'all_categories': all_categories,
        'season_votes': season_votes,
        'top_shows_by_category': top_shows_by_category
    })

pollProject/voteStatistics/templates/voteStatistics/category_statistics.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <form method="get">
        <select name="category" onchange="this.form.submit()" class="category-select">
            <option value="">--Select Category--</option>
            
            {% for category in all_categories %}
                <option value="{{ category }}" {% if category == selected_category %}selected{% endif %}>{{ category }}</option>
            {% endfor %}
        </select>
    </form>
    
    {% for category, seasons in categories.items %}
        <div class="category-statistics">
            <h2 class="category-name">{{ category.name }} of {% now "Y" %}</h2>
            <div class="category">
                {% for season, data in seasons.items %}
                    <div class="season">
                        <h3>Season: {{ season.name }}</h3>
                        <div class="question-grid">
                            {% for question_data in data.questions %}
                                <div class="question" >
                                    <p>Total votes: {{ question_data.total_votes }}</p>
                                    <table>
                                        <tr>
                                            <th>Choice Text</th>
                                            <th>Votes</th>
                                            <th>{{ season.name }} Weight</th>
                                            <th>Weighted Score</th>
                                        </tr>
                                        {% for vote in question_data.choice_votes|dictsortreversed:"weighted_score" %}
                                            <tr>
                                                <td>{{ vote.choice__choice_text }}</td>
                                                <td>{{ vote.total_votes }}</td>
                                                <td>{{ vote.season_weight|floatformat:2 }}</td>
                                                <td>{{ vote.weighted_score|floatformat:2 }}</td>
                                            </tr>
                                        {% endfor %}
                                    </table>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endfor %}

    {% for category, top_shows in top_shows_by_category.items %}
    <div class="top-shows">
        <h2>{{ category.name }} of 2023</h2>
        <div class="top-shows-container">
            <ul class="show-list">
                {% for show in top_shows %}
                    <li class="show-entry {% if forloop.counter == 1 %}gold{% elif forloop.counter == 2 %}silver{% elif forloop.counter == 3 %}bronze{% endif %}">
                        <label for="choice{{ forloop.counter }}" class="choice-label">
                            <img src="{{ show.choice_image }}" alt="{{ show.choice_text }}" class="choice-image" />
                            {{ show.choice_text }}
                        </label>
                        <div class="show-details">
                            <h3>{{ show.show }}</h3>
                            <p>Weighted Score: {{ show.weighted_score|floatformat:2 }}</p>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endfor %}

{% endblock %}

pollProject/voteStatistics/templates/voteStatistics/vote_statistics.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}
  <head>  
    <title>Vote Statistics</title>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
      body {
        font-family: 'Arial', sans-serif;
      }

      h1 {
        text-align: center;
      }
    </style>
  </head>
  <body>
    <h1>Vote Statistics</h1>
    <a href="{% url 'voteStatistics:category_statistics' %}">Category Statistics</a>
    <form id="filterForm" method="get" action="{% url 'voteStatistics:vote_statistics' %}">
      <label for="year">Filter by Year:</label>
      <select name="year" id="year">
        <option value="">All</option>
        {% for year in years %}
          <option value="{{ year }}" {% if selected_year == year %}selected{% endif %}>{{ year }}</option>
        {% endfor %}
      </select>

      <label for="season">Filter by Season:</label>
      <select name="season" id="season">
        <option value="">Pick a Season</option>
        {% for season in seasons %}
          <option value="{{ season.id }}" {% if selected_season == season.id %}selected{% endif %}>{{ season.name }} {{ season.year }}</option>
        {% endfor %}
      </select>

      <label for="question">Select Question:</label>
      <select name="question" id="question">
        <option value="" {% if not selected_question %}selected{% endif %}>Pick a Question</option>
        {% for question in all_questions %}
          <option value="{{ question.id }}" {% if selected_question == question.id %}selected{% endif %}>{{ question.question_text }}</option>
        {% endfor %}
      </select>
    </form>

    <div style="display: flex; justify-content: space-between;">
      <div style="width: 70%;">
        <canvas id="chart" width="1200" height="800"></canvas>
      </div>
    </div>

    <form>
      <label for="choice">Select Choice:</label>
      <select id="choice">
      </select>

      <label for="data">Select Data:</label>
      <select id="data">
        <option value="gender_percentage">Gender Percentage</option>
        <option value="region_percentage">Region Percentage</option>
        <option value="age_percentage">Age Percentage</option>
      </select>
    </form>

    <div style="width: 70%;">
      <canvas id="pieChart" width="1200" height="800"></canvas>
      <div id="pieChartData"></div>
    </div>

    <div id="votersInfo"></div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script type="text/javascript">
      var isFormSubmitted = false;

      function submitForm() {
        if (!isFormSubmitted) {
          isFormSubmitted = true;
          document.getElementById('filterForm').submit();
          updateChart();  // Update chart after form submission
        }
      }

      document.getElementById('year').addEventListener('change', submitForm);
      document.getElementById('season').addEventListener('change', submitForm);
      document.getElementById('question').addEventListener('change', function() {
        isFormSubmitted = false;
        submitForm();
      });

      var question_votes_data = JSON.parse('{{ question_votes_json | safe }}');
      var ctx = document.getElementById('chart').getContext('2d');
      var colors = [
        'rgba(255, 99, 132, 0.2)',
        'rgba(54, 162, 235, 0.2)',
        'rgba(255, 206, 86, 0.2)',
        'rgba(75, 192, 192, 0.2)',
        'rgba(153, 102, 255, 0.2)',
        'rgba(255, 159, 64, 0.2)',
        'rgba(199, 199, 199, 0.2)',
        'rgba(83, 102, 255, 0.2)',
        'rgba(255, 99, 255, 0.2)',
        'rgba(255, 209, 102, 0.2)',
      ];

      function truncateLabel(label, maxLength) {
        return label.length > maxLength ? label.substring(0, maxLength) + '...' : label;
      }

      var chart = new Chart(ctx, {
        type: 'bar',
        data: {
          labels: [],
          datasets: [],
        },
        options: {
          indexAxis: 'y',
          scales: {
            x: {
              beginAtZero: true,
            },
          },
          plugins: {
            legend: {
              position: 'top',
            },
          },
        },
      });

      var pieCtx = document.getElementById('pieChart').getContext('2d');
      var pieChart = new Chart(pieCtx, {
        type: 'pie',
        data: {
          labels: [],
          datasets: [{
            data: [],
            backgroundColor: colors,
          }],
        },
        options: {
          plugins: {
            legend: {
              position: 'top',
            },
          },
        },
      });

      function updatePieChart() {
        var selectedQuestion = document.getElementById('question').value;
        var selectedChoice = document.getElementById('choice').value;
        var selectedData = document.getElementById('data').value;

        var filteredData = question_votes_data.filter(qv => qv.question.id == selectedQuestion);
        var choiceData = filteredData.flatMap(qv => qv.top_votes.filter(vote => vote.choice__choice_text == selectedChoice));

        if (choiceData.length > 0) {
          pieChart.data.labels = Object.keys(choiceData[0][selectedData]);
          pieChart.data.datasets[0].data = Object.values(choiceData[0][selectedData]);
          pieChart.update();
        }

        var pieChartDataDiv = document.getElementById('pieChartData');
        pieChartDataDiv.innerHTML = '';
        for (var i = 0; i < pieChart.data.labels.length; i++) {
            var label = pieChart.data.labels[i];
            var data = pieChart.data.datasets[0].data[i];
            pieChartDataDiv.innerHTML += label + ': ' + data.toFixed(2) + '%<br>';
        }
        var votersInfoDiv = document.getElementById('votersInfo');
        pieChartDataDiv.innerHTML += votersInfoDiv.innerHTML;
      }

      document.getElementById('choice').addEventListener('change', updatePieChart);
      document.getElementById('data').addEventListener('change', updatePieChart);

      function updateChart() {
        var selectedQuestion = document.getElementById('question').value;
        var filteredData = question_votes_data.filter(qv => qv.question.id == selectedQuestion);
        chart.data.datasets = [];

        filteredData.forEach((qv, index) => {
          var color = colors[index % colors.length];
          var dataset = {
            label: qv.question.question_text,
            data: qv.top_votes.map(vote => vote.total_votes),
            backgroundColor: colors,
          };
          chart.data.datasets.push(dataset);
        });

        chart.data.labels = filteredData.flatMap(qv => qv.top_votes.map(vote => truncateLabel(vote.choice__choice_text, 20)));
        chart.update();

        var votersInfoDiv = document.getElementById('votersInfo');
        votersInfoDiv.innerHTML = '';
        
        var choiceDropdown = document.getElementById('choice');
        choiceDropdown.innerHTML = '';
        filteredData.flatMap(qv => qv.top_votes).forEach(vote => {
          var option = document.createElement('option');
          option.value = vote.choice__choice_text;
          option.textContent = truncateLabel(vote.choice__choice_text, 20);
          choiceDropdown.appendChild(option);
        });

        updatePieChart();
      }

      // Initial update of the question dropdown
      updateChart();
    </script>
  </body>
{% endblock %}